pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'jdk-17'
    }

    stages {
        stage('Build') {
            steps {
                //sh 'cd Eurder'
                sh 'mvn -f Eurder/pom.xml clean install -DskipTests'
            }
        }
        stage('Test-Stage') {
            steps {
                sh 'cd Eurder'
                sh 'mvn test'
            }
        }
    }

    post {
        always {
            publishCoverage adapters: [jacocoAdapter('**/target/site/jacoco/jacoco.xml')]
            junit '**/target/surefire-reports/*.xml'
        }
    }
}